### PR TITLE
Use new system for mapping NVMe volumes

### PR DESCRIPTION
**Pull request by orangejulius**
This apparently works better with new nitro AWS instances, and will fix issues on instances where EBS or NVMe volumes are not accessible via `/dev/sd*`

It uses the scripts from https://github.com/oogali/ebs-automatic-nvme-mapping mentioned in https://github.com/pelias/terraform-elasticsearch/pull/26

Closes https://github.com/pelias/terraform-elasticsearch/pull/26

### CODE REVIEW

**Comment by missinglink** [comment]
Just checking that this will still allow creating instances with *either* EBS or NVMe disks?

**Comment by orangejulius** [comment]
Yup, it works fine on both.

Here's what the block mappings and symlinks look like on an NVMe instance:

```
ubuntu@ip-172-20-46-85:~$ lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0          7:0    0   92M  1 loop /snap/lxd/29631
loop1          7:1    0 33.7M  1 loop /snap/snapd/21761
loop2          7:2    0 68.9M  1 loop /snap/core22/1666
loop3          7:3    0 59.5M  1 loop /snap/core20/2437
loop4          7:4    0 22.9M  1 loop /snap/amazon-ssm-agent/9882
nvme2n1      259:0    0    1G  0 disk 
nvme1n1      259:1    0    5G  0 disk /usr/local/var/log/elasticsearch
nvme0n1      259:2    0    8G  0 disk 
├─nvme0n1p1  259:3    0  7.9G  0 part /
└─nvme0n1p15 259:4    0   99M  0 part /boot/efi
nvme3n1      259:5    0  1.3T  0 disk 
nvme4n1      259:6    0  1.3T  0 disk /usr/local/var/data/elasticsearch
ubuntu@ip-172-20-46-85:~$ ls -lh /dev/sd*
lrwxrwxrwx 1 root root 7 Nov 21 15:19 /dev/sda1 -> nvme0n1
lrwxrwxrwx 1 root root 7 Nov 21 15:19 /dev/sdb -> nvme2n1
lrwxrwxrwx 1 root root 7 Nov 21 15:19 /dev/sdc -> nvme1n1
```

**Review by missinglink — APPROVED** [review]
Yeah looks good, hard to know how well it functions from only reading the code.

**Comment by orangejulius** [comment]
Absolutely, for changes here everything has to be tested :)

**Pull request merged**
